version: '3.8'
services:
  user-api:
    build:
      context: ./user-api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/user # Adjust database name as needed
    volumes:
      - ./user-api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb

  user-app-ui:
    build:
      context: ./user-app-ui
    ports:
      - "80:80"
    depends_on:
      - user-api

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
