version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_URI=mongodb://mongo:27017/user
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
